-- DROP PROCEDURE UDP_CREATE_TABLES;

CREATE PROCEDURE UDP_CREATE_TABLES
AS
BEGIN
    DROP TABLE IF EXISTS points;
    DROP TABLE IF EXISTS polygons;
DROP TABLE IF EXISTS linestrings;
CREATE TABLE points(
    id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    point GEOMETRY NOT NULL,
    label VARCHAR(255) NOT NULL
);
CREATE TABLE polygons(
    id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    polygon GEOMETRY NOT NULL,
    label VARCHAR(255) NOT NULL
);
CREATE TABLE linestrings(
    id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    linestring GEOMETRY NOT NULL,
    label VARCHAR(255) NOT NULL
);
END;